# Generated by Django 3.0.5 on 2020-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200517_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='initial_date',
        ),
        migrations.AddField(
            model_name='project',
            name='intial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
