# Generated by Django 3.0.5 on 2020-05-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200518_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='intial_date',
        ),
    ]
