# Generated by Django 3.0.5 on 2020-05-18 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_project_intial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intial_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
